[package]
name = "redis-derive"
version = "0.1.1"
edition = "2021"
authors = ["Michael van Straten"]
description = "This crate implements the redis::FromRedisValue and redis::ToRedisArgs traits from mitsuhiko / redis-rs for any struct"
repository = "https://github.com/michaelvanstraten/redis-derive"
license = "MIT"


[dependencies]
quote = "1.0.10"
syn = {version = "1.0", features = ["extra-traits"]}

[lib]
proc-macro = true
